; Philly Mesh Micro Node: https://phillymesh.net
[env:PhillyMesh_MicroNode]
custom_meshtastic_hw_model = 267
custom_meshtastic_hw_model_slug = PHILLYMESH_MICRONODE
custom_meshtastic_architecture = nrf52840
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = Philly Mesh Micro Node
custom_meshtastic_tags = PhillyMesh

extends = nrf52840_base
board = phillymesh_micronode
board_level = pr
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/PhillyMesh_MicroNode
  -I src/platform/nrf52/softdevice
  -I src/platform/nrf52/softdevice/nrf52
  -DCONFIG_NFCT_PINS_AS_GPIOS=1
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/PhillyMesh_MicroNode>
debug_tool = jlink
; If not set we will default to uploading over serial (first it forces bootloader entry by talking 1200bps to cdcacm)
;upload_protocol = jlink
